=== AludraTest/aludratest/schema/1.1/testdata.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="unqualified" version="1.0" targetNamespace="http://aludratest.org/testdata" xmlns:tns="http://aludratest.org/testdata" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="testdata" type="tns:testData"/>

  <xs:complexType name="testData">
    <xs:sequence>
      <xs:element name="metadata" type="tns:testDataMetadata" form="qualified"/>
      <xs:element name="configurations" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="configuration" type="tns:testDataConfiguration" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="version" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="testDataMetadata">
    <xs:sequence>
      <xs:element name="segments" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="segment" type="tns:testDataSegmentMetadata" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="testDataSegmentMetadata">
    <xs:sequence>
      <xs:element name="fields" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="field" type="tns:testDataFieldMetadata" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="dataClassName" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="testDataFieldMetadata">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="fieldType" type="tns:testDataFieldType"/>
    <xs:attribute name="subTypeClassName" type="xs:string"/>
    <xs:attribute name="formatterPattern" type="xs:string"/>
    <xs:attribute name="formatterLocale" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="testDataConfiguration">
    <xs:sequence>
      <xs:element name="segments" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="segment" type="tns:testDataConfigurationSegment" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="ignored" type="xs:boolean"/>
    <xs:attribute name="ignoredReason" type="xs:string"/>
    <xs:attribute name="externalTestId" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="testDataConfigurationSegment">
    <xs:sequence>
      <xs:element name="fieldValues" form="qualified" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="fieldValue" type="tns:testDataFieldValue" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="testDataFieldValue">
    <xs:sequence>
      <xs:choice minOccurs="0">
        <xs:element name="value" type="tns:stringValue" form="qualified"/>
        <xs:element name="stringValues" type="tns:stringValueList" form="qualified"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="script" type="xs:boolean"/>
  </xs:complexType>

  <xs:simpleType name="stringValue">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:complexType name="stringValueList">
    <xs:sequence>
      <xs:element name="value" type="tns:stringValue" form="qualified" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="testDataFieldType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="STRING"/>
      <xs:enumeration value="DATE"/>
      <xs:enumeration value="NUMBER"/>
      <xs:enumeration value="BOOLEAN"/>
      <xs:enumeration value="OBJECT"/>
      <xs:enumeration value="OBJECT_LIST"/>
      <xs:enumeration value="STRING_LIST"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== AludraTest/aludratest/src/test/resources/org/aludratest/testcase/data/xml/XmlBasedTestDataProviderTest/timetravel.testdata.xml
<?xml version="1.0" encoding="UTF-8" ?>

<testdata xmlns="http://aludratest.org/testdata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://aludratest.org/testdata http://aludratest.github.io/aludratest/schema/draft/testdata.xsd" 
	version="1.0">
    <metadata>
        <segments>
        <segment name="stringObject"
        	dataClassName="org.aludratest.util.data.StringData">
        <fields>
        	<field name="value" fieldType="DATE" formatterPattern="yyyy-MM-dd HH:mm"/>
        </fields>
        </segment>
        <segment name="secondObject" dataClassName="org.aludratest.util.data.StringData">
        	<fields>
        		<field name="value" />
        	</fields>
        </segment>
        </segments>
    </metadata>

    <configurations>
    <configuration name="config1">
    	<segments>
    		<segment name="stringObject">
    			<fieldValues>
    				<fieldValue name="value" script="true">
    					<value>new Date(&quot;8 Mar 2015 23:58:00&quot;)</value>
    				</fieldValue>
    			</fieldValues>
    		</segment>
    		<segment name="secondObject">
    			<fieldValues>
    				<fieldValue name="value" script="true">
    					<value>&quot;Test &quot; + timetravel(new Date(1472342400000)).format(&quot;yyyy-mm-dd&quot;)</value>
    				</fieldValue>
    			</fieldValues>
    		</segment>
    	</segments>
    </configuration>
    </configurations>
</testdata>

=== AludraTest/aludratest/src/test/resources/org/aludratest/scheduler/impl/DeferredEvalTestClass/deferred.testdata.xml
<?xml version="1.0" encoding="UTF-8" ?>

<testdata xmlns="http://aludratest.org/testdata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://aludratest.org/testdata http://aludratest.github.io/aludratest/schema/draft/testdata.xsd" 
	version="1.0">
    <metadata>
        <segments>
        <segment name="stringObject"
        	dataClassName="org.aludratest.util.data.StringData">
        <fields>
        	<field name="value" fieldType="STRING"/>
        </fields>
        </segment>
        </segments>
    </metadata>

    <configurations>
    <configuration name="config1">
    	<segments>
    		<segment name="stringObject">
    			<fieldValues>
    				<fieldValue name="value" script="true">
    					<value>new org.aludratest.scheduler.impl.DeferredEvalTestClass().setField()</value>
    				</fieldValue>
    			</fieldValues>
    		</segment>
    	</segments>
    </configuration>
    </configurations>
</testdata>

=== AludraTest/aludratest/src/test/resources/org/aludratest/testcase/data/xml/XmlBasedTestDataProviderTest/multi.testdata.xml
<?xml version="1.0" encoding="UTF-8" ?>

<testdata xmlns="http://aludratest.org/testdata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://aludratest.org/testdata http://aludratest.github.io/aludratest/schema/draft/testdata.xsd" 
	version="1.0">
    <metadata>
        <segments>
        <segment name="complexObject"
        	dataClassName="org.aludratest.testcase.data.xml.ComplexData">
        <fields>
        	<field name="name"/>
        	<field name="subData" fieldType="OBJECT" subTypeClassName="org.aludratest.util.data.StringData"/>
        </fields>
        </segment>
        <segment name="stringObject"
        	dataClassName="org.aludratest.util.data.StringData">
        <fields>
        	<field name="value"/>
        </fields>
        </segment>
        <segment name="complexObject.subData"
        	dataClassName="org.aludratest.util.data.StringData">
        <fields>
        	<field name="value" fieldType="STRING"/>
        </fields>
        </segment>
        </segments>
    </metadata>

    <configurations>
    <configuration name="config1">
    	<segments>
    		<segment name="complexObject">
    			<fieldValues>
    				<fieldValue name="name">
    					<value>The Config1</value>
    				</fieldValue>
    				<fieldValue name="subData"></fieldValue>
    			</fieldValues>
    		</segment>
    		<segment name="stringObject">
    			<fieldValues>
    				<fieldValue name="value">
    					<value>Some value ending with space </value>
    				</fieldValue>
    			</fieldValues>
    		</segment>
    		<!-- intentional left out of subData to assert null object -->
    	</segments>
    </configuration>
    <configuration name="config2">
    	<segments>
    		<segment name="complexObject">
    			<fieldValues>
    				<fieldValue name="name">
    					<value>The Config2</value>
    				</fieldValue>
    				<fieldValue name="subData"></fieldValue>
    			</fieldValues>
    		</segment>
    		<segment name="stringObject">
    			<fieldValues>
    				<fieldValue name="value">
    					<value>Dragons be here</value>
    				</fieldValue>
    			</fieldValues>
    		</segment>
    		<segment name="complexObject.subData">
    			<!-- empty, but should still generate empty object. -->
    			<fieldValues>
    			</fieldValues>
    		</segment>
    	</segments>
    </configuration>
    <configuration name="config3" ignored="true">
    	<segments>
    		<segment name="complexObject">
    			<fieldValues>
    				<fieldValue name="name">
    					<value>The Config2</value>
    				</fieldValue>
    				<fieldValue name="subData"></fieldValue>
    			</fieldValues>
    		</segment>
    		<segment name="stringObject">
    			<fieldValues>
    				<fieldValue name="value">
    					<value>Dragons be here</value>
    				</fieldValue>
    			</fieldValues>
    		</segment>
    		<segment name="complexObject.subData">
    			<!-- empty, but should still generate empty object. -->
    			<fieldValues>
    			<fieldValue name="value"></fieldValue>
    			</fieldValues>
    		</segment>
    	</segments>
    </configuration>    
    </configurations>
</testdata>
